# Generated by Django 3.1.1 on 2021-01-29 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210128_2350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
